### ISSUE TITLE
Update to Python3

### ISSUE THREAD

**Issue by oculus99** [derpycode/cgenie.muffin#203]
Seem that Python code in cgenie.muffin is python27 code.
Python3 is newer and more popular.

**Comment by derpycode** [comment]
Indeed.
However, given my lack of time to update things like this, I pretty much work on the basis that until something is 'broken' for someone and they are unable to use the model at all, I don't try and 'fix' it ... :o)

**Comment by evansmn** [comment]
Hi Andy,

I recently upgraded my OS to Debian/Bookworm, which has both python3 and python2.7.  I'm not in the same boat as the original poster, as I dislike all versions of python about equally :).  But now I can't compile the model at all, not even with specifying that I want to call #! /usr/bin/python2.7 in the scripts. So maybe I can help sort this, but I think I need some help.

I am troubleshooting with a fresh git install from January 11, 2024, and I am compiling a base-config and user-config just as for LAB8.1 in muffin.pdf.  To start, I think I've brought all your python2.7 code up to python 3 standard (mainly: has_key --> in; and print () and some variables needing to be converted to strings before comparing to dictionaries, AFAICT.  nccomp.py still wants module cdms, which I can't find, so that's still broken.).  

But resolving the python code still leads me to the model not getting to the compile stage.  In runmuffin.sh, it seems to get through to 'make cleanall' and then throws

"Error: : unrecognised settings in config file (perhaps a typo?):"

and then a list, in python dict form, of all the configuration settings.

Now I can inspect the temporary .xml file that is produced, and newbie that I am, I can't find any obvious problems in what's there.  I did check it vs. the definitions.xml that is in the .SPIN cgenie_output for that lab experiment (source: muffin.CBE.p_worjh2.BASESFeTDTL.FeMIP.SPIN.tar.gz).  But I'm unsure I can tell the difference between a typo (or set of them, if my python revisions to translate_config.py are bad) and some new parameters that don't exist in the .SPIN configuration, such as <param name="opt_bio_remin_oxidize_NH4toNO3">.

To try and simplify the number of parameters to check for errors, I have also experimented with copies of muffin.C.fm0000aa.NONE.config (only the atmosphere model enabled) and EXAMPLE.p0650e.SPIN with PI pCO2.  I get the same error: unrecognized settings.

It seems runmuffin.sh gets to l. 383, section (9), and then fails.

Do you know where this error originates?  That might help me get further.  I tried grepping through files in my ~/cgenie, could not find.

Thank you in advance for any help,
Mike

**Comment by derpycode** [comment]
Hi Mike,

I am just about (next week) to get someone work on ensuring that everything is python3 
friendly.

So one option, if you can wait a couple of weeks ... is to wait a couple of weeks.

I also have not followed up on the pull request and comments from some time ago ... which 
might be the 'original poster' you referred to ... too many things divided by zero time ... this 
only works out well if you divide in MATLAB ...

Otherwise -- did make testbiogem run successfully after installing?

FYI: I do most of my development and testing in Ubuntu and as far as I remember from the 
last time I created a fresh Ubuntu install, I am not doing anything different from the Ubuntu 
install section in the muffin manual. Then again, maybe I should explicitly re-make an 
Ubuntu box and follow through.


/andy

**Comment by evansmn** [comment]
Andy,  thanks - 
 
I was referring to the thread on github: "Update to Python3 #203" by oculus99, where I am writing this.  

I can certainly wait - would it be helpful to send you anything I have done?

In the meantime, I can get things running by changing the environment variable setting in genie.job to

TRANSLATE_CONFIG="python2.7 ./translate_config.py"

and changing all .py file shebangs in genie-main/*.py scripts to /usr/bin/python2.7.  

Yes, I could have followed your installation instructions to link /usr/bin/python to /usr/bin/python2.7.  I was afraid to break some other python dependent things on this system.  That is my bad for having a multipurpose system.

For EXP8.1 as a test, I had to comment out the user-config setting:

#eg_par_ecogem_timeseries_file='timeseries_sites_NONE.eco'

because it was not recognized.  But then compilation completes and the experiment runs.

Thanks again,
-Mike

**Comment by derpycode** [comment]
Thanks.

I am going to have someone look into all the python this week.

I expect to have a python3-friendly branch off of master by the end of next week.
(I cannot update master as I'll have 100s of python2.7 users after by blood.)

In the medium-term, there will be an entirely new release, which will be python 3 by default 
and have a simple default netCDF installation.

Re. eg_par_ecogem_timeseries_file='timeseries_sites_NONE.eco'

I'll look into this. I suspect it is because eg_par_ecogem_timeseries_file is on a branch which 
I have not merged yet. I could have this resolved on a time-scale of about a week too.


/andy

**Comment by derpycode** [comment]
You can find a python3 version on:
master.python3
This is up-to-date with master and will be kept that way (and eventually become a new release).
I have carried out a few tests and it work fine.
It does currently assume that your python v3 installation is called python3. (We may improve on this fixed name assumption shortly.)
Please open up a new Issue if you find something in/about the new python code that is functioning correctly.
